#메인에서만 접근(수정) 가능
name: CI

on:
  pull_request:
    branches:
      - main
      - dev
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CODECOV_VERSION: "v0.1.15"

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test -- --coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: Umunjeong/email
